development:
  adapter: postgresql
  encoding: utf8
  database: blog_dev
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: utf8
  database: blog_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: utf8
  database: blog
  pool: 5
  username: postgres
  password: postgres
